[package]
name = "lukso_validator_check"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.12", features = ["rustls-tls"] }
scraper = "0.19"
anyhow = "1"
futures = "0.3"